### ISSUE TITLE
dynamic namespace computation

### ISSUE THREAD

**Issue by fabienli** [xif-fr/dokuwiki-plugin-catlist#35]
Hello,

I would like to use catlist plugin in the sidebar, where it would display the list of pages in the current namespace (the namespace relevant to the main page currently displayed).
I can provide a first PR with a simple implementation (that works at least for my need).
Are there others interested by such option? was this already planned for a future release?

**Comment by xif-fr** [comment]
Hi,

It doesn't work to just call catlist without a namespace ? There is already this line in the code:
``
if ($ns == '') $ns = '.'; // If there is nothing, we take the current namespace
``

But it may not work because it is in the ``handle`` function and not in the ``render`` function as you did in your PR.

**Comment by fabienli** [comment]
Hi,

as you explain in your above last sentence, the namespace taken is the one relevant to where the page is stored (e.g. sidebar page is at the root of the wiki) and not where we're currently browsing into the wiki.

**Comment by xif-fr** [comment]
Yes, in that case, you did the right thing. I'll pull that ASAP
